/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { OrderWrapper } from '../model/orderWrapper';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class OrderHistoryEndpointService {

    protected basePath = 'https://localhost:3000/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * findAllOrdersForCustomer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findAllOrdersForCustomerUsingGET1(observe?: 'body', reportProgress?: boolean): Observable<Array<OrderWrapper>>;
    public findAllOrdersForCustomerUsingGET1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<OrderWrapper>>>;
    public findAllOrdersForCustomerUsingGET1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<OrderWrapper>>>;
    public findAllOrdersForCustomerUsingGET1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<OrderWrapper>>(`${this.basePath}/orders/summary`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findOrderById
     * 
     * @param orderId orderId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findOrderByIdUsingGET1(orderId: number, observe?: 'body', reportProgress?: boolean): Observable<OrderWrapper>;
    public findOrderByIdUsingGET1(orderId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OrderWrapper>>;
    public findOrderByIdUsingGET1(orderId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OrderWrapper>>;
    public findOrderByIdUsingGET1(orderId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (orderId === null || orderId === undefined) {
            throw new Error('Required parameter orderId was null or undefined when calling findOrderByIdUsingGET1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<OrderWrapper>(`${this.basePath}/orders/${encodeURIComponent(String(orderId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * findOrdersForCustomer
     * 
     * @param orderStatus orderStatus
     * @param orderNumber orderNumber
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findOrdersForCustomerUsingGET1(orderStatus?: string, orderNumber?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<OrderWrapper>>;
    public findOrdersForCustomerUsingGET1(orderStatus?: string, orderNumber?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<OrderWrapper>>>;
    public findOrdersForCustomerUsingGET1(orderStatus?: string, orderNumber?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<OrderWrapper>>>;
    public findOrdersForCustomerUsingGET1(orderStatus?: string, orderNumber?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (orderStatus !== undefined) {
            queryParameters = queryParameters.set('orderStatus', <any>orderStatus);
        }
        if (orderNumber !== undefined) {
            queryParameters = queryParameters.set('orderNumber', <any>orderNumber);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<OrderWrapper>>(`${this.basePath}/orders`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
