/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { RatingSummaryWrapper } from '../model/ratingSummaryWrapper';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class RatingEndpointService {

    protected basePath = 'https://localhost:3000/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getRatingsForItem
     * 
     * @param itemId itemId
     * @param ratingType ratingType
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRatingsForItemUsingDELETE1(itemId: string, ratingType?: string, observe?: 'body', reportProgress?: boolean): Observable<RatingSummaryWrapper>;
    public getRatingsForItemUsingDELETE1(itemId: string, ratingType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RatingSummaryWrapper>>;
    public getRatingsForItemUsingDELETE1(itemId: string, ratingType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RatingSummaryWrapper>>;
    public getRatingsForItemUsingDELETE1(itemId: string, ratingType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemId === null || itemId === undefined) {
            throw new Error('Required parameter itemId was null or undefined when calling getRatingsForItemUsingDELETE1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ratingType !== undefined) {
            queryParameters = queryParameters.set('ratingType', <any>ratingType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<RatingSummaryWrapper>(`${this.basePath}/ratings/${encodeURIComponent(String(itemId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRatingsForItem
     * 
     * @param itemId itemId
     * @param ratingType ratingType
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRatingsForItemUsingGET1(itemId: string, ratingType?: string, observe?: 'body', reportProgress?: boolean): Observable<RatingSummaryWrapper>;
    public getRatingsForItemUsingGET1(itemId: string, ratingType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RatingSummaryWrapper>>;
    public getRatingsForItemUsingGET1(itemId: string, ratingType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RatingSummaryWrapper>>;
    public getRatingsForItemUsingGET1(itemId: string, ratingType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemId === null || itemId === undefined) {
            throw new Error('Required parameter itemId was null or undefined when calling getRatingsForItemUsingGET1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ratingType !== undefined) {
            queryParameters = queryParameters.set('ratingType', <any>ratingType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<RatingSummaryWrapper>(`${this.basePath}/ratings/${encodeURIComponent(String(itemId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRatingsForItem
     * 
     * @param itemId itemId
     * @param ratingType ratingType
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRatingsForItemUsingHEAD1(itemId: string, ratingType?: string, observe?: 'body', reportProgress?: boolean): Observable<RatingSummaryWrapper>;
    public getRatingsForItemUsingHEAD1(itemId: string, ratingType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RatingSummaryWrapper>>;
    public getRatingsForItemUsingHEAD1(itemId: string, ratingType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RatingSummaryWrapper>>;
    public getRatingsForItemUsingHEAD1(itemId: string, ratingType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemId === null || itemId === undefined) {
            throw new Error('Required parameter itemId was null or undefined when calling getRatingsForItemUsingHEAD1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ratingType !== undefined) {
            queryParameters = queryParameters.set('ratingType', <any>ratingType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.head<RatingSummaryWrapper>(`${this.basePath}/ratings/${encodeURIComponent(String(itemId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRatingsForItem
     * 
     * @param itemId itemId
     * @param ratingType ratingType
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRatingsForItemUsingOPTIONS1(itemId: string, ratingType?: string, observe?: 'body', reportProgress?: boolean): Observable<RatingSummaryWrapper>;
    public getRatingsForItemUsingOPTIONS1(itemId: string, ratingType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RatingSummaryWrapper>>;
    public getRatingsForItemUsingOPTIONS1(itemId: string, ratingType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RatingSummaryWrapper>>;
    public getRatingsForItemUsingOPTIONS1(itemId: string, ratingType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemId === null || itemId === undefined) {
            throw new Error('Required parameter itemId was null or undefined when calling getRatingsForItemUsingOPTIONS1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ratingType !== undefined) {
            queryParameters = queryParameters.set('ratingType', <any>ratingType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.options<RatingSummaryWrapper>(`${this.basePath}/ratings/${encodeURIComponent(String(itemId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRatingsForItem
     * 
     * @param itemId itemId
     * @param ratingType ratingType
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRatingsForItemUsingPATCH1(itemId: string, ratingType?: string, observe?: 'body', reportProgress?: boolean): Observable<RatingSummaryWrapper>;
    public getRatingsForItemUsingPATCH1(itemId: string, ratingType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RatingSummaryWrapper>>;
    public getRatingsForItemUsingPATCH1(itemId: string, ratingType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RatingSummaryWrapper>>;
    public getRatingsForItemUsingPATCH1(itemId: string, ratingType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemId === null || itemId === undefined) {
            throw new Error('Required parameter itemId was null or undefined when calling getRatingsForItemUsingPATCH1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ratingType !== undefined) {
            queryParameters = queryParameters.set('ratingType', <any>ratingType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.patch<RatingSummaryWrapper>(`${this.basePath}/ratings/${encodeURIComponent(String(itemId))}`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRatingsForItem
     * 
     * @param itemId itemId
     * @param ratingType ratingType
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRatingsForItemUsingPOST1(itemId: string, ratingType?: string, observe?: 'body', reportProgress?: boolean): Observable<RatingSummaryWrapper>;
    public getRatingsForItemUsingPOST1(itemId: string, ratingType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RatingSummaryWrapper>>;
    public getRatingsForItemUsingPOST1(itemId: string, ratingType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RatingSummaryWrapper>>;
    public getRatingsForItemUsingPOST1(itemId: string, ratingType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemId === null || itemId === undefined) {
            throw new Error('Required parameter itemId was null or undefined when calling getRatingsForItemUsingPOST1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ratingType !== undefined) {
            queryParameters = queryParameters.set('ratingType', <any>ratingType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<RatingSummaryWrapper>(`${this.basePath}/ratings/${encodeURIComponent(String(itemId))}`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRatingsForItem
     * 
     * @param itemId itemId
     * @param ratingType ratingType
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRatingsForItemUsingPUT1(itemId: string, ratingType?: string, observe?: 'body', reportProgress?: boolean): Observable<RatingSummaryWrapper>;
    public getRatingsForItemUsingPUT1(itemId: string, ratingType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RatingSummaryWrapper>>;
    public getRatingsForItemUsingPUT1(itemId: string, ratingType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RatingSummaryWrapper>>;
    public getRatingsForItemUsingPUT1(itemId: string, ratingType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (itemId === null || itemId === undefined) {
            throw new Error('Required parameter itemId was null or undefined when calling getRatingsForItemUsingPUT1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (ratingType !== undefined) {
            queryParameters = queryParameters.set('ratingType', <any>ratingType);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.put<RatingSummaryWrapper>(`${this.basePath}/ratings/${encodeURIComponent(String(itemId))}`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
