/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { CustomerAddressWrapper } from '../model/customerAddressWrapper';
import { CustomerPaymentWrapper } from '../model/customerPaymentWrapper';
import { CustomerWrapper } from '../model/customerWrapper';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ReactCustomerEndpointService {

    protected basePath = 'https://localhost:3000/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * addCustomerPayment
     * 
     * @param customerPaymentWrapper customerPaymentWrapper
     * @param paymentMethodNonce payment_method_nonce
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addCustomerPaymentUsingPOST3(customerPaymentWrapper: CustomerPaymentWrapper, paymentMethodNonce: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CustomerPaymentWrapper>>;
    public addCustomerPaymentUsingPOST3(customerPaymentWrapper: CustomerPaymentWrapper, paymentMethodNonce: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CustomerPaymentWrapper>>>;
    public addCustomerPaymentUsingPOST3(customerPaymentWrapper: CustomerPaymentWrapper, paymentMethodNonce: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CustomerPaymentWrapper>>>;
    public addCustomerPaymentUsingPOST3(customerPaymentWrapper: CustomerPaymentWrapper, paymentMethodNonce: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (customerPaymentWrapper === null || customerPaymentWrapper === undefined) {
            throw new Error('Required parameter customerPaymentWrapper was null or undefined when calling addCustomerPaymentUsingPOST3.');
        }
        if (paymentMethodNonce === null || paymentMethodNonce === undefined) {
            throw new Error('Required parameter paymentMethodNonce was null or undefined when calling addCustomerPaymentUsingPOST3.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (paymentMethodNonce !== undefined) {
            queryParameters = queryParameters.set('payment_method_nonce', <any>paymentMethodNonce);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Array<CustomerPaymentWrapper>>(`${this.basePath}/customer/customer-payment`,
            customerPaymentWrapper,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteAddress
     * 
     * @param customerAddressId customerAddressId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteAddressUsingDELETE1(customerAddressId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<CustomerAddressWrapper>>;
    public deleteAddressUsingDELETE1(customerAddressId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CustomerAddressWrapper>>>;
    public deleteAddressUsingDELETE1(customerAddressId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CustomerAddressWrapper>>>;
    public deleteAddressUsingDELETE1(customerAddressId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (customerAddressId === null || customerAddressId === undefined) {
            throw new Error('Required parameter customerAddressId was null or undefined when calling deleteAddressUsingDELETE1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<Array<CustomerAddressWrapper>>(`${this.basePath}/customer/remove-address/${encodeURIComponent(String(customerAddressId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCurrentCustomer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentCustomerUsingDELETE1(observe?: 'body', reportProgress?: boolean): Observable<CustomerWrapper>;
    public getCurrentCustomerUsingDELETE1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CustomerWrapper>>;
    public getCurrentCustomerUsingDELETE1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CustomerWrapper>>;
    public getCurrentCustomerUsingDELETE1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<CustomerWrapper>(`${this.basePath}/customer/current`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCurrentCustomer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentCustomerUsingGET1(observe?: 'body', reportProgress?: boolean): Observable<CustomerWrapper>;
    public getCurrentCustomerUsingGET1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CustomerWrapper>>;
    public getCurrentCustomerUsingGET1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CustomerWrapper>>;
    public getCurrentCustomerUsingGET1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<CustomerWrapper>(`${this.basePath}/customer/current`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCurrentCustomer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentCustomerUsingHEAD1(observe?: 'body', reportProgress?: boolean): Observable<CustomerWrapper>;
    public getCurrentCustomerUsingHEAD1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CustomerWrapper>>;
    public getCurrentCustomerUsingHEAD1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CustomerWrapper>>;
    public getCurrentCustomerUsingHEAD1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.head<CustomerWrapper>(`${this.basePath}/customer/current`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCurrentCustomer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentCustomerUsingOPTIONS1(observe?: 'body', reportProgress?: boolean): Observable<CustomerWrapper>;
    public getCurrentCustomerUsingOPTIONS1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CustomerWrapper>>;
    public getCurrentCustomerUsingOPTIONS1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CustomerWrapper>>;
    public getCurrentCustomerUsingOPTIONS1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.options<CustomerWrapper>(`${this.basePath}/customer/current`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCurrentCustomer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentCustomerUsingPATCH1(observe?: 'body', reportProgress?: boolean): Observable<CustomerWrapper>;
    public getCurrentCustomerUsingPATCH1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CustomerWrapper>>;
    public getCurrentCustomerUsingPATCH1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CustomerWrapper>>;
    public getCurrentCustomerUsingPATCH1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.patch<CustomerWrapper>(`${this.basePath}/customer/current`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCurrentCustomer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentCustomerUsingPOST1(observe?: 'body', reportProgress?: boolean): Observable<CustomerWrapper>;
    public getCurrentCustomerUsingPOST1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CustomerWrapper>>;
    public getCurrentCustomerUsingPOST1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CustomerWrapper>>;
    public getCurrentCustomerUsingPOST1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<CustomerWrapper>(`${this.basePath}/customer/current`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCurrentCustomer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentCustomerUsingPUT1(observe?: 'body', reportProgress?: boolean): Observable<CustomerWrapper>;
    public getCurrentCustomerUsingPUT1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CustomerWrapper>>;
    public getCurrentCustomerUsingPUT1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CustomerWrapper>>;
    public getCurrentCustomerUsingPUT1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.put<CustomerWrapper>(`${this.basePath}/customer/current`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * makePaymentDefault
     * 
     * @param customerPaymentId customerPaymentId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public makePaymentDefaultUsingPOST1(customerPaymentId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<CustomerPaymentWrapper>>;
    public makePaymentDefaultUsingPOST1(customerPaymentId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CustomerPaymentWrapper>>>;
    public makePaymentDefaultUsingPOST1(customerPaymentId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CustomerPaymentWrapper>>>;
    public makePaymentDefaultUsingPOST1(customerPaymentId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (customerPaymentId === null || customerPaymentId === undefined) {
            throw new Error('Required parameter customerPaymentId was null or undefined when calling makePaymentDefaultUsingPOST1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<Array<CustomerPaymentWrapper>>(`${this.basePath}/customer/customer-payment/${encodeURIComponent(String(customerPaymentId))}/default`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateCustomerPayment
     * 
     * @param customerPaymentWrapper customerPaymentWrapper
     * @param customerPaymentId customerPaymentId
     * @param paymentMethodNonce payment_method_nonce
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateCustomerPaymentUsingPUT3(customerPaymentWrapper: CustomerPaymentWrapper, customerPaymentId: number, paymentMethodNonce: string, observe?: 'body', reportProgress?: boolean): Observable<Array<CustomerPaymentWrapper>>;
    public updateCustomerPaymentUsingPUT3(customerPaymentWrapper: CustomerPaymentWrapper, customerPaymentId: number, paymentMethodNonce: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CustomerPaymentWrapper>>>;
    public updateCustomerPaymentUsingPUT3(customerPaymentWrapper: CustomerPaymentWrapper, customerPaymentId: number, paymentMethodNonce: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CustomerPaymentWrapper>>>;
    public updateCustomerPaymentUsingPUT3(customerPaymentWrapper: CustomerPaymentWrapper, customerPaymentId: number, paymentMethodNonce: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (customerPaymentWrapper === null || customerPaymentWrapper === undefined) {
            throw new Error('Required parameter customerPaymentWrapper was null or undefined when calling updateCustomerPaymentUsingPUT3.');
        }
        if (customerPaymentId === null || customerPaymentId === undefined) {
            throw new Error('Required parameter customerPaymentId was null or undefined when calling updateCustomerPaymentUsingPUT3.');
        }
        if (paymentMethodNonce === null || paymentMethodNonce === undefined) {
            throw new Error('Required parameter paymentMethodNonce was null or undefined when calling updateCustomerPaymentUsingPUT3.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (paymentMethodNonce !== undefined) {
            queryParameters = queryParameters.set('payment_method_nonce', <any>paymentMethodNonce);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<Array<CustomerPaymentWrapper>>(`${this.basePath}/customer/customer-payment/${encodeURIComponent(String(customerPaymentId))}`,
            customerPaymentWrapper,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
