/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CountryWrapper } from './countryWrapper';
import { ISOCountryWrapper } from './iSOCountryWrapper';
import { PhoneWrapper } from './phoneWrapper';
import { StateWrapper } from './stateWrapper';


export interface AddressWrapper {
    addressLine1?: string;
    addressLine2?: string;
    addressLine3?: string;
    city?: string;
    companyName?: string;
    country?: CountryWrapper;
    firstName?: string;
    id?: number;
    isBusiness?: boolean;
    isDefault?: boolean;
    isoCountryAlpha2?: ISOCountryWrapper;
    isoCountrySubdivision?: string;
    lastName?: string;
    phoneFax?: PhoneWrapper;
    phonePrimary?: PhoneWrapper;
    phoneSecondary?: PhoneWrapper;
    postalCode?: string;
    state?: StateWrapper;
    stateProvinceRegion?: string;
}
