/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryAttributeWrapper } from './categoryAttributeWrapper';
import { Character } from './character';
import { ProductWrapper } from './productWrapper';


export interface CategoryWrapper {
    active?: boolean;
    activeEndDate?: Date;
    activeStartDate?: Date;
    archived?: Character;
    category?: Array<CategoryWrapper>;
    categoryAttribute?: Array<CategoryAttributeWrapper>;
    description?: string;
    id?: number;
    name?: string;
    product?: Array<ProductWrapper>;
    relatedProduct?: Array<ProductWrapper>;
    url?: string;
    urlKey?: string;
}
