/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressWrapper } from './addressWrapper';
import { AdjustmentWrapper } from './adjustmentWrapper';
import { BroadleafEnumerationTypeWrapper } from './broadleafEnumerationTypeWrapper';
import { FulfillmentGroupItemWrapper } from './fulfillmentGroupItemWrapper';
import { FulfillmentOptionWrapper } from './fulfillmentOptionWrapper';
import { Money } from './money';
import { PhoneWrapper } from './phoneWrapper';
import { TaxDetailWrapper } from './taxDetailWrapper';


export interface FulfillmentGroupWrapper {
    address?: AddressWrapper;
    fulfillmentGroupAdjustment?: Array<AdjustmentWrapper>;
    fulfillmentGroupItem?: Array<FulfillmentGroupItemWrapper>;
    fulfillmentOption?: FulfillmentOptionWrapper;
    fulfillmentPrice?: Money;
    fulfillmentType?: BroadleafEnumerationTypeWrapper;
    id?: number;
    orderId?: number;
    phone?: PhoneWrapper;
    status?: string;
    taxDetail?: Array<TaxDetailWrapper>;
    total?: Money;
}
