/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BroadleafEnumerationTypeWrapper } from './broadleafEnumerationTypeWrapper';
import { Character } from './character';


export interface FulfillmentOptionWrapper {
    archived?: Character;
    description?: string;
    fulfillmentType?: BroadleafEnumerationTypeWrapper;
    id?: number;
    name?: string;
}
