/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Money } from './money';
import { OrderItemWrapper } from './orderItemWrapper';
import { TaxDetailWrapper } from './taxDetailWrapper';


export interface FulfillmentGroupItemWrapper {
    fulfillmentGroupId?: number;
    id?: number;
    orderItem?: OrderItemWrapper;
    orderItemId?: number;
    quantity?: number;
    taxDetail?: Array<TaxDetailWrapper>;
    totalItemAmount?: Money;
    totalTax?: Money;
}
