/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RatingDetailWrapper } from './ratingDetailWrapper';
import { ReviewFeedbackWrapper } from './reviewFeedbackWrapper';


export interface ReviewDetailWrapper {
    author?: string;
    helpfulCount?: number;
    id?: number;
    notHelpfulCount?: number;
    ratingDetail?: RatingDetailWrapper;
    reviewFeedback?: Array<ReviewFeedbackWrapper>;
    reviewStatus?: string;
    reviewSubmittedDate?: Date;
    reviewText?: string;
}
