/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MapElementWrapper } from './mapElementWrapper';
import { Money } from './money';
import { OrderItemAttributeWrapper } from './orderItemAttributeWrapper';
import { ProductWrapper } from './productWrapper';


export interface ConfigurableOrderItemWrapper {
    additionalAttributes?: Array<MapElementWrapper>;
    childOrderItems?: Array<ConfigurableOrderItemWrapper>;
    displayPrice?: Money;
    hasConfigurationError?: boolean;
    isMultiSelect?: boolean;
    isUpdateRequest?: boolean;
    itemAttributes?: Array<OrderItemAttributeWrapper>;
    maxQuantity?: number;
    minQuantity?: number;
    orderItemId?: number;
    orderItemIndex?: number;
    originalOrderItemId?: number;
    overrideRetailPrice?: Money;
    overrideSalePrice?: Money;
    parentOrderItemId?: number;
    product?: ProductWrapper;
    productChoices?: Array<ConfigurableOrderItemWrapper>;
    productId?: number;
    quantity?: number;
    skuId?: number;
}
