/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';
import { CustomerAttributeWrapper } from './customerAttributeWrapper';


export interface CustomerWrapper {
    archived?: Character;
    customerAttribute?: Array<CustomerAttributeWrapper>;
    emailAddress?: string;
    firstName?: string;
    id?: number;
    lastName?: string;
    registered?: boolean;
}
