/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressWrapper } from './addressWrapper';
import { CustomerWrapper } from './customerWrapper';
import { MapElementWrapper } from './mapElementWrapper';


export interface CustomerPaymentWrapper {
    additionalField?: Array<MapElementWrapper>;
    billingAddress?: AddressWrapper;
    cardName?: string;
    cardType?: string;
    customer?: CustomerWrapper;
    expirationDate?: Date;
    id?: number;
    isDefault?: boolean;
    lastFour?: string;
    paymentGatewayType?: string;
    paymentToken?: string;
    paymentType?: string;
}
