/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';
import { DynamicSkuPricesWrapper } from './dynamicSkuPricesWrapper';
import { MediaWrapper } from './mediaWrapper';
import { Money } from './money';
import { ProductAttributeWrapper } from './productAttributeWrapper';
import { ProductOptionWrapper } from './productOptionWrapper';
import { RelatedProductWrapper } from './relatedProductWrapper';
import { SkuBundleItemWrapper } from './skuBundleItemWrapper';
import { SkuWrapper } from './skuWrapper';
import { PromotionMessageDTOWrapper } from 'src/main/webapp/app/bl-app/bl-api';


export interface ProductWrapper {
    active?: boolean;
    activeEndDate?: Date;
    activeStartDate?: Date;
    additionalSkus?: Array<SkuWrapper>;
    archived?: Character;
    bundleItemsRetailPrice?: Money;
    bundleItemsSalePrice?: Money;
    crossSaleProduct?: Array<RelatedProductWrapper>;
    defaultCategoryId?: number;
    defaultSku?: SkuWrapper;
    description?: string;
    dynamicSkuPrices?: DynamicSkuPricesWrapper;
    id?: number;
    longDescription?: string;
    manufacturer?: string;
    media?: Array<MediaWrapper>;
    model?: string;
    name?: string;
    primaryMedia?: MediaWrapper;
    priority?: number;
    productAttribute?: Array<ProductAttributeWrapper>;
    productOption?: Array<ProductOptionWrapper>;
    promoMessage?: string;
    promotionMessages?: { [key: string]: Array<PromotionMessageDTOWrapper>; };
    retailPrice?: Money;
    salePrice?: Money;
    skuBundleItem?: Array<SkuBundleItemWrapper>;
    upsaleProduct?: Array<RelatedProductWrapper>;
    url?: string;
}
