/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RatingDetailWrapper } from './ratingDetailWrapper';
import { ReviewDetailWrapper } from './reviewDetailWrapper';


export interface RatingSummaryWrapper {
    averageRating?: number;
    currentCustomerReview?: ReviewDetailWrapper;
    id?: number;
    itemId?: string;
    numberOfRatings?: number;
    numberOfReviews?: number;
    rating?: Array<RatingDetailWrapper>;
    ratingType?: string;
    review?: Array<ReviewDetailWrapper>;
}
