/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';
import { ProductWrapper } from './productWrapper';


export interface RelatedProductWrapper {
    archived?: Character;
    id?: number;
    product?: ProductWrapper;
    promotionalMessage?: string;
    sequence?: number;
}
