/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SearchFacetValueWrapper } from './searchFacetValueWrapper';


export interface SearchFacetWrapper {
    active?: boolean;
    canMultiselect?: boolean;
    fieldName?: string;
    label?: string;
    values?: Array<SearchFacetValueWrapper>;
}
