/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductWrapper } from './productWrapper';
import { SearchFacetWrapper } from './searchFacetWrapper';
import { SkuWrapper } from './skuWrapper';


export interface SearchResultsWrapper {
    page?: number;
    pageSize?: number;
    product?: Array<ProductWrapper>;
    searchFacet?: Array<SearchFacetWrapper>;
    sku?: Array<SkuWrapper>;
    totalPages?: number;
    totalResults?: number;
}
