/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';
import { Money } from './money';
import { SkuWrapper } from './skuWrapper';


export interface SkuBundleItemWrapper {
    active?: boolean;
    archived?: Character;
    bundleId?: number;
    description?: string;
    id?: number;
    longDescription?: string;
    name?: string;
    productId?: number;
    quantity?: number;
    retailPrice?: Money;
    salePrice?: Money;
    sku?: SkuWrapper;
}
