/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from './character';
import { DimensionWrapper } from './dimensionWrapper';
import { Money } from './money';
import { WeightWrapper } from './weightWrapper';


export interface SkuWrapper {
    active?: boolean;
    activeEndDate?: Date;
    activeStartDate?: Date;
    archived?: Character;
    available?: boolean;
    description?: string;
    dimension?: DimensionWrapper;
    id?: number;
    inventoryType?: string;
    name?: string;
    retailPrice?: Money;
    salePrice?: Money;
    weight?: WeightWrapper;
}
