/**
 * Broadleaf Commerce API
 * The default Broadleaf Commerce APIs
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BroadleafEnumerationTypeWrapper } from './broadleafEnumerationTypeWrapper';
import { Money } from './money';


export interface TaxDetailWrapper {
    amount?: Money;
    country?: string;
    currency?: string;
    id?: number;
    jurisdictionName?: string;
    rate?: number;
    region?: string;
    taxName?: string;
    taxType?: BroadleafEnumerationTypeWrapper;
}
