export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './breadcrumbsEndpoint.service';
import { BreadcrumbsEndpointService } from './breadcrumbsEndpoint.service';
export * from './checkoutEndpoint.service';
import { CheckoutEndpointService } from './checkoutEndpoint.service';
export * from './customerEndpoint.service';
import { CustomerEndpointService } from './customerEndpoint.service';
export * from './fulfillmentEndpoint.service';
import { FulfillmentEndpointService } from './fulfillmentEndpoint.service';
export * from './menuEndpoint.service';
import { MenuEndpointService } from './menuEndpoint.service';
export * from './messageEndpoint.service';
import { MessageEndpointService } from './messageEndpoint.service';
export * from './orderHistoryEndpoint.service';
import { OrderHistoryEndpointService } from './orderHistoryEndpoint.service';
export * from './previewTemplateController.service';
import { PreviewTemplateControllerService } from './previewTemplateController.service';
export * from './promotionMessageEndpoint.service';
import { PromotionMessageEndpointService } from './promotionMessageEndpoint.service';
export * from './ratingEndpoint.service';
import { RatingEndpointService } from './ratingEndpoint.service';
export * from './reactCartEndpoint.service';
import { ReactCartEndpointService } from './reactCartEndpoint.service';
export * from './reactCatalogEndpoint.service';
import { ReactCatalogEndpointService } from './reactCatalogEndpoint.service';
export * from './reactCheckoutEndpoint.service';
import { ReactCheckoutEndpointService } from './reactCheckoutEndpoint.service';
export * from './reactCustomerEndpoint.service';
import { ReactCustomerEndpointService } from './reactCustomerEndpoint.service';
export * from './reactPageEndpoint.service';
import { ReactPageEndpointService } from './reactPageEndpoint.service';
export * from './relatedProductsEndpoint.service';
import { RelatedProductsEndpointService } from './relatedProductsEndpoint.service';
export * from './seoEndpoint.service';
import { SeoEndpointService } from './seoEndpoint.service';
export * from './swaggerDocsReloadEndpoint.service';
import { SwaggerDocsReloadEndpointService } from './swaggerDocsReloadEndpoint.service';
export * from './themeEndpoint.service';
import { ThemeEndpointService } from './themeEndpoint.service';
export * from './wishlistEndpoint.service';
import { WishlistEndpointService } from './wishlistEndpoint.service';
export const APIS = [BasicErrorControllerService, BreadcrumbsEndpointService, CheckoutEndpointService, CustomerEndpointService, FulfillmentEndpointService, MenuEndpointService, MessageEndpointService, OrderHistoryEndpointService, PreviewTemplateControllerService, PromotionMessageEndpointService, RatingEndpointService, ReactCartEndpointService, ReactCatalogEndpointService, ReactCheckoutEndpointService, ReactCustomerEndpointService, ReactPageEndpointService, RelatedProductsEndpointService, SeoEndpointService, SwaggerDocsReloadEndpointService, ThemeEndpointService, WishlistEndpointService];
